### PR TITLE
Handle gutter destruction error

### LINKED ISSUE #65: Uncaught Error: The given gutter cannot be removed because it is not within this GutterContainer.
[Enter steps to reproduce below:]
On `linter`@[13728e7](https://github.com/steelbrain/linter/commit/13728e7b5479910f7599aa3679a93dc32c1b1c53) and `linter-ui-default`@47f739c29911abacfb21e472a1681ae91b1614bd

1. Open a file that shows issues
2. Close the file after the issues have been reported by the linters (sometimes this is enough to trigger)
3. Open the file again (in preview mode, doesn't seem to be actually necessary though)
4. Close the file (usually before linters would have a chance to report back, but even triggers when waiting)

This seems a bit random, but the above is the best steps I have found to reproduce.

**Atom Version**: 1.7.0-beta4
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package, v0.0.3

### Stack Trace

Uncaught Error: The given gutter cannot be removed because it is not within this GutterContainer.

```
At C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\gutter-container.js:100

Error: The given gutter cannot be removed because it is not within this GutterContainer.
    at GutterContainer.module.exports.GutterContainer.removeGutter (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\gutter-container.js:100:15)
    at Gutter.module.exports.Gutter.destroy (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\gutter.js:27:30)
    at Editor.dispose (C:/Users/Landon Abney/Documents/GitHub-release/linter-ui-default/lib/editor.js:103:19)
    at C:/Users/Landon Abney/Documents/GitHub-release/linter-ui-default/lib/editor.js:50:12
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at TextEditor.module.exports.TextEditor.destroyed (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\text-editor.js:295:27)
    at TextEditor.module.exports.Model.destroy (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\model.js:31:58)
    at Pane.module.exports.Pane.destroyItem (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\pane.js:638:18)
    at Pane.module.exports.Pane.destroyActiveItem (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\pane.js:616:12)
    at Workspace.module.exports.Workspace.destroyActivePaneItem (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\workspace.js:692:35)
    at Workspace.module.exports.Workspace.closeActivePaneItemOrEmptyPaneOrWindow (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\workspace.js:731:21)
    at atom-workspace.commandRegistry.add.core:close (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\register-default-commands.js:211:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\Landon Abney\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -4:47.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:43.5.0 core:save (atom-text-editor.editor.is-focused)
     -3:05.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:50.3.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -2:38.9.0 core:save (atom-text-editor.editor.is-focused)
     -2:31 project-find:show (atom-text-editor.editor.is-focused)
     -2:26.3.0 find-and-replace:focus-next (atom-text-editor.editor.mini.is-focused)
     -2:25.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:25.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:18.7.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -2:17.5.0 core:copy (atom-text-editor.editor.is-focused)
     -1:17.1.0 project-find:show (atom-text-editor.editor.is-focused)
     -1:16.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:58.7.0 core:select-all (atom-text-editor.editor.mini.is-focused)
  3x -0:49.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:15.4.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      ".bin",
      "fast-eslint",
      "linter-flow",
      "atom-typescript",
      "markdown-preview-plus",
      "git-control",
      "git-history",
      "linter-gjslint",
      "language-markdown",
      "linter-tidy",
      "language-chef",
      "linter-csslint",
      "linter-bootlint",
      "linter-scss-lint",
      "linter-jscs",
      "svn",
      "linter-pylint",
      "linter-pep8"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "linter-ui-default": {}
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.7
atom-beautify, v0.29.1
autocomplete-python, v1.7.2
docblockr, v0.7.3
editorconfig, v1.2.4
file-watcher, v0.4.0
highlight-selected, v0.11.2
language-docker, v1.1.6
language-elixir, v0.12.3
language-haml, v0.24.0
language-ini, v1.16.0
language-powershell, v2.1.0
language-r, v0.4.0
language-reg, v0.0.0
linter, v1.11.4
linter-alex, v2.0.0
linter-coffeelint, v1.1.2
linter-docker, v0.1.2
linter-elixirc, v1.1.7
linter-erb, v1.0.2
linter-eslint, v7.1.3
linter-flake8, v1.13.0
linter-foodcritic, v0.5.2
linter-golinter, v1.2.0
linter-haml, v1.2.0
linter-htmlhint, v1.1.1
linter-javac, v1.8.1
linter-js-yaml, v1.2.5
linter-jshint, v2.0.4
linter-jsonlint, v1.2.2
linter-lintr, v1.0.4
linter-lua, v1.0.2
linter-markdown, v1.5.0
linter-perl, v0.7.2
linter-perlcritic, v0.3.3
linter-php, v1.2.0
linter-phpcs, v1.3.1
linter-phpmd, v1.4.1
linter-pylama, v0.2.9
linter-rails-best-practices, v0.2.2
linter-reek, v2.1.5
linter-rubocop, v0.4.7
linter-ruby, v1.2.2
linter-stylelint, v2.1.1
linter-tslint, v0.9.1
linter-ui-default, v0.0.3
mapfile-grammar, v0.1.0
minimap, v4.21.0
minimap-find-and-replace, v4.5.0
minimap-git-diff, v4.2.0
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-selection, v4.4.0
pigments, v0.26.0
seti-syntax, v0.4.2
seti-ui, v0.9.2
tab-control, v0.6.9
toggle-quotes, v1.0.0
trailing-spaces, v0.3.2

# Dev
No dev packages
```

### PR DESCRIPTION
**Pull request by steelbrain**
Fixes #65

### CODE REVIEW

File: lib/editor.js [hunk 1]
```diff
@@ -100,7 +100,9 @@ export default class Editor {
     this.emitter.emit('did-destroy')
     this.subscriptions.dispose()
     if (this.gutter) {
-      this.gutter.destroy()
+      try {
+        this.gutter.destroy()
+      } catch (_) { /* No Op */ }
```
Comment (Arcanemagus) [inline lib/editor.js]: Maybe put in a comment that this is a workaround for what appears to be an Atom internal bug?

Comment (steelbrain) [inline lib/editor.js]: Done

**Comment by steelbrain** [comment]
Merging in as reviewer comments have been taken care of
